### ISSUE TITLE
Can`t even start in dev mode

### ISSUE THREAD

**Issue by say1j** [trinitrotoluene/StatusWatchdog#10]
Drops when going to localhost:5000 on dev mode with dotnet watch run
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No file provider has been configured to process the supplied file.
   at Microsoft.AspNetCore.Mvc.Infrastructure.VirtualFileResultExecutor.GetFileInformation(VirtualFileResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.VirtualFileResultExecutor.ExecuteAsync(ActionContext context, VirtualFileResult result)
   at Microsoft.AspNetCore.Mvc.VirtualFileResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
What i need to do in dev?
Api key was pasted (DDdb+rovzYczvCqCXgFJBllHddj8FHR9aLTSdQ98kXA=), but any way

![image](https://user-images.githubusercontent.com/31889581/96368507-d699d000-115c-11eb-81c3-efb55c4d602a.png)

**Comment by trinitrotoluene** [comment]
Hi, can you confirm for me that you've got the client submodule pulled locally? That exception occurs when the middleware that serves the SPA can't find the index.html file that it serves to load it.

**Comment by say1j** [comment]
$ dotnet watch run (from here)
![image](https://user-images.githubusercontent.com/31889581/96386614-f523b980-11a4-11eb-8b88-e4e687b010d3.png)
result browser
![image](https://user-images.githubusercontent.com/31889581/96386628-0d93d400-11a5-11eb-9539-e5fd1bf97182.png)
result visual
![image](https://user-images.githubusercontent.com/31889581/96386635-184e6900-11a5-11eb-888f-1df0cba91dbc.png)


> Hi, can you confirm for me that you've got the client submodule pulled locally? That exception occurs when the middleware that serves the SPA can't find the index.html file that it serves to load it.

**Comment by trinitrotoluene** [comment]
The error is coming from the backend expecting a `wwwroot` folder to be present to serve files from, and this folder is created by the client app during deployment.

To pull in the missing client-app submodule
```
$ git submodule update --init --recursive
```
then install and run the client app in `src/StatusWatchdog/client-app`
```
$ npm install
$ npm run watch
```

once it's running you can start `dotnet watch run` in a new terminal (you can do this from vscode) and both projects will live-reload as you edit them.

That said, if you just want to test/get an idea of the state the project is currently in, you might want to just run it using the docker-compose configuration in the README. It'll save you the extra work of configuring a PostgreSQL database for the backend to talk to.

**Comment by say1j** [comment]
> The error is coming from the backend expecting a `wwwroot` folder to be present to serve files from, and this folder is created by the client app during deployment.
> 
> To pull in the missing client-app submodule
> 
> ```
> $ git submodule update --init --recursive
> ```
> 
> then install and run the client app in `src/StatusWatchdog/client-app`
> 
> ```
> $ npm install
> $ npm run watch
> ```
> 
> once it's running you can start `dotnet watch run` in a new terminal (you can do this from vscode) and both projects will live-reload as you edit them.
> 
> That said, if you just want to test/get an idea of the state the project is currently in, you might want to just run it using the docker-compose configuration in the README. It'll save you the extra work of configuring a PostgreSQL database for the backend to talk to.

okay, i`ll try it
